### ISSUE TITLE
create a task list for the application

### ISSUE THREAD

**Issue by lordadamson** [Ketabuk/Ketabuk-AndroidApp#2]
basically compare the app to the webfront and see what needs to be done and create issues accordingly.

**Comment by lordadamson** [comment]
@mohamed-habib

**Comment by mohamed-habib** [comment]
Added issues to implement the pages that are already implemented at the web front: #3 #4 #5 #6 .

**Comment by lordadamson** [comment]
thanks love :D I'll close now :heart:
